version: '3'

services:
  backend:
    build: backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres

  frontend:
    build: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  client:
    image: "nginx"
    ports:
      - "8000:80"
    volumes:
      - ./src:/usr/share/nginx/html